FROM ubuntu:24.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    gh \
    screen \
    curl \
    ca-certificates \
    openssh-server \
    npm \
    vim \
    sudo && \
    rm -rf /var/lib/apt/lists/*

RUN apt-get remove -y libnode-dev libnode72 || true

RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash - &&\
    apt-get install -y nodejs &&\
    npm install -g n &&\
    n 22.17.1 &&\
    apt-get purge -y nodejs npm &&\
    rm -rf /var/lib/apt/lists/*

RUN npm install -g pnpm@10.13.1

# Check if ubuntu user exists before creating
RUN id -u ubuntu &>/dev/null || useradd -m -s /bin/bash ubuntu

WORKDIR /home/ubuntu

RUN mkdir -p /home/ubuntu/.ssh && \
    chown -R ubuntu:ubuntu /home/ubuntu/.ssh && \
    chmod 700 /home/ubuntu/.ssh

RUN mkdir /var/run/sshd && \
    echo 'PermitRootLogin no' >> /etc/ssh/sshd_config && \
    echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config && \
    echo 'AllowUsers ubuntu' >> /etc/ssh/sshd_config

EXPOSE 22 3000 8000