services:
  taxi-proxy:
    container_name: taxi-proxy-shared
    restart: always
    image: nginx:1.24.0
    ports:
      - "${PROXY_PORT:?err}:80"
    networks:
      - shared-proxy
      - shared-ipvlan

  taxi-mongo:
    container_name: taxi-mongo-shared
    restart: always
    image: mongo:4.4
    networks:
      - shared-backend
      - shared-ipvlan

volumes:
  taxi-mongo-data:
    external: true

networks:
  shared-proxy:
  shared-backend:
  shared-ipvlan:
    driver: ipvlan
    driver_opts:
      parent: ens19
    ipam:
      config:
        - subnet: 10.251.1.0/24
          gateway: 10.251.1.1