services:
  taxi-testuser1:
    container_name: taxi-testuser1
    restart: always
    build:
      context: ./taxi-dev-servers
      dockerfile: Dockerfile
    networks:
      shared-backend:
      shared-ipvlan:
        ipv4_address: 10.251.1.10 # TODO: Edit here
    volumes:
      - ./taxi-dev-servers/taxi-front-testuser1:/home/ubuntu/taxi-front
      - ./taxi-dev-servers/taxi-back-testuser1:/home/ubuntu/taxi-back
    command: ["/usr/sbin/sshd", "-D"]

networks:
  shared-backend:
    external: true
    name: taxi-dc_shared-backend
  shared-ipvlan:
    external: true
    name: taxi-dc_shared-ipvlan
