services:
  taxi-testuser1: # TODO: Edit here
    container_name: taxi-testuser1 # TODO: Edit here
    restart: always
    build:
      context: ./taxi-dev-servers
      dockerfile: Dockerfile
    networks:
      shared-backend:
      shared-ipvlan:
        ipv4_address: 10.251.1.10 # TODO: Edit here
    volumes:
      - ./taxi-dev-servers/testuser1/taxi-front:/home/ubuntu/taxi-front # TODO: Edit here
      - ./taxi-dev-servers/testuser1/taxi-back:/home/ubuntu/taxi-back # TODO: Edit here
    command: ["/usr/sbin/sshd", "-D"]

networks:
  shared-backend:
    external: true
    name: taxi-dc_shared-backend
  shared-ipvlan:
    external: true
    name: taxi-dc_shared-ipvlan
