services:
  taxi-dns:
    container_name: taxi-dns
    restart: always
    image: jpillora/dnsmasq
    volumes:
      - ./taxi-dns/dnsmasq.conf:/etc/dnsmasq.conf:rw
    cap_add:
      - NET_ADMIN
    env_file:
      - .env
    environment:
      - HTTP_USER=${HTTP_USER}
      - HTTP_PASS=${HTTP_PASS}
    networks:
      shared-backend:
      shared-ipvlan:
        ipv4_address: 10.251.1.2
  taxi-mongo-shared:
    container_name: taxi-mongo-shared
    restart: always
    image: mongo:4.4
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ./taxi-mongodb:/data/db
    networks:
      shared-backend:
      shared-ipvlan:
        ipv4_address: 10.251.1.3

networks:
  shared-backend:
    name: taxi-dc_shared-backend
  shared-ipvlan:
    name: taxi-dc_shared-ipvlan
    driver: ipvlan
    driver_opts:
      parent: ens19
      mode: l3
    ipam:
      config:
        - subnet: 10.251.1.0/24
          gateway: 10.251.1.1