services:
  taxi-{{ username }}:
    container_name: taxi-{{ username }}
    image: taxi-{{ username }}
    restart: always
    networks:
      shared-backend:
      shared-ipvlan:
        ipv4_address: {{ ipv4_address }}
    volumes:
      - ../users/{{ username }}:/home/ubuntu
    command: ["/usr/sbin/sshd", "-D"]

networks:
  shared-backend:
    external: true
    name: taxi-dc_shared-backend
  shared-ipvlan:
    external: true
    name: taxi-dc_shared-ipvlan
