services:
  taxi-proxy:
    container_name: taxi-proxy-shared
    restart: always
    image: nginx:1.24.0
    networks:
      shared-ipvlan:
        ipv4_address: 10.251.1.2

  taxi-mongo:
    container_name: taxi-mongo-shared
    restart: always
    image: mongo:4.4
    networks:
      shared-backend:
      shared-ipvlan:
        ipv4_address: 10.251.1.3

volumes:
  taxi-mongo-data:
    external: true

networks:
  shared-backend:
    name: taxi-dc_shared-backend
  shared-ipvlan:
    name: taxi-dc_shared-ipvlan
    driver: ipvlan
    driver_opts:
      parent: ens19
      mode: l3
    ipam:
      config:
        - subnet: 10.251.1.0/24
          gateway: 10.251.1.1